Repository wecode-bootcamp-korea/35-2nd-SeSac-backend, pull requests merged in 2022-08, with the labels that each got.

#1 [35기 김동규] 프로젝트 초기 세팅
  .gitignore
  fresh_us/__init__.py
  fresh_us/asgi.py
  fresh_us/settings.py
  fresh_us/urls.py
  fresh_us/wsgi.py
  manage.py
  requirements.txt
Labels: 멘토 리뷰 요청

#2 [35기 김동규] 데이터베이스 모델링
  comments/__init__.py
  comments/admin.py
  comments/apps.py
  comments/migrations/0001_initial.py
  comments/migrations/0002_rename_post_id_comment_post_and_more.py
  comments/migrations/__init__.py
  comments/models.py
  comments/tests.py
  comments/views.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  fresh_us/settings.py
  posts/__init__.py
  posts/admin.py
  posts/apps.py
  posts/migrations/0001_initial.py
  posts/migrations/0002_rename_category_name_category_name_and_more.py
  posts/migrations/__init__.py
  posts/models.py
  posts/tests.py
  posts/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_kakao_id.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: 멘토 리뷰 요청

#3 [35기 김동규] 데이터데이스 칼럼명 변경
  posts/migrations/0003_rename_hashtag_hashtag_name.py
  users/migrations/0003_user_profile_image_url.py
  users/models.py
Labels: 멘토 리뷰 요청

#4 [35기 박서윤] 게시글 리스트 페이지 구현
  fresh_us/settings.py
  fresh_us/urls.py
  posts/tests.py
  posts/urls.py
  posts/views.py
  requirements.txt
Labels: 멘토 리뷰 요청

#5 [35기 김동규] 카카오 소셜 로그인 구현
  core/utils/kakao_api.py
  core/utils/login_decorator.py
  fresh_us/settings.py
  fresh_us/urls.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Conflict 해결 요청

#8 [35기 박서윤] 게시물 POST API 구현
  core/utils.py
  fresh_us/settings.py
  posts/urls.py
  posts/views.py
  requirements.txt
  users/utils.py
Labels: 멘토 리뷰 요청

#6 [35기 김동규] 댓글 기능 구현
  comments/tests.py
  comments/urls.py
  comments/views.py
  core/utils/kakao_api.py
  fresh_us/settings.py
  fresh_us/urls.py
Labels: 멘토 리뷰 요청

#9 [35기 박서윤] 게시물 DELETE API 구현
  core/util.py
  core/utils/kakao_api.py
  posts/urls.py
  posts/views.py
Labels: 멘토 리뷰 요청

#10 [35기 박서윤] post GET API 구현
  fresh_us/settings.py
  posts/urls.py
  posts/views.py
Labels: 멘토 리뷰 요청

#14 [35기 김동규] 카카오 API 토큰 만료 추가
  core/utils/kakao_api.py
  users/views.py
Labels: 멘토 리뷰 요청

#15 [35기 박서윤] post GET 데코레이터 추가
  posts/views.py
Labels: 멘토 리뷰 요청

#17 [35기 김동규] 댓글 기능 문제사항 수정
  comments/views.py
  core/utils/login_decorator.py
  users/tests.py
Labels: 멘토 리뷰 요청

#18 [35기 김동규] 삭제된 로그인 데코레이터 추가
  core/utils/login_decorator.py
  users/views.py
Labels: 멘토 리뷰 요청

#22 hot_fix
  fresh_us/settings.py
  users/views.py
Labels: 완료
